name: Build Label Studio image

env:
  REPOSITORY_NAME: digital-pathology/label-studio
  DOCKERFILE_PATH: Dockerfile
  DOCKER_ROOT_PATH: .

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Determine image tag
      run: |
        echo "DO_DEPLOY=${{ github.ref=='refs/heads/master' || contains(github.ref,'refs/tags/') }}" >> $GITHUB_ENV
        if [ "${{ contains(github.ref,'refs/tags/') }}" == "true" ]
        then
          tag="${{github.ref}}"
          echo "IMAGE_TAG=release-${tag:10}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=dev-${{ github.sha }}" >> $GITHUB_ENV
        fi


    - name: Build image
      run: |
        docker build --build-arg -t $REPOSITORY_NAME:$IMAGE_TAG -f $DOCKERFILE_PATH $DOCKER_ROOT_PATH

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag, and push image to DockerHub
      if: ${{ env.DO_DEPLOY=='true' }}    
      run: |
        docker tag $REPOSITORY_NAME:$IMAGE_TAG $REPOSITORY_NAME:$IMAGE_TAG
        docker push $REPOSITORY_NAME:$IMAGE_TAG